// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PadTime.Infrastructure.Persistence;

#nullable disable

namespace PadTime.Infrastructure.Migrations
{
    [DbContext(typeof(PadTimeDbContext))]
    partial class PadTimeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PadTime.Domain.Billing.OrganizerDebt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("organizer_debts", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Billing.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at_utc");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("purpose");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("state");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("MatchId");

                    b.HasIndex("MemberId");

                    b.ToTable("payments", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Booking.Match", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CourtId")
                        .HasColumnType("uuid")
                        .HasColumnName("court_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at_utc");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid")
                        .HasColumnName("organizer_id");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("SiteId");

                    b.HasIndex("StartAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("CourtId", "StartAtUtc")
                        .IsUnique()
                        .HasFilter("status <> 'Cancelled'");

                    b.ToTable("matches", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Booking.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at_utc");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("MemberId");

                    b.HasIndex("MatchId", "MemberId")
                        .IsUnique();

                    b.ToTable("participants", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Subject")
                        .IsUnique();

                    b.ToTable("members", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Site.Court", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_courts_created_at_utc");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_courts_is_active");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_courts_site_id");

                    b.HasIndex("SiteId", "IsActive")
                        .HasDatabaseName("IX_courts_site_active");

                    b.HasIndex("SiteId", "Label")
                        .IsUnique()
                        .HasDatabaseName("IX_courts_site_id_label_unique");

                    b.HasIndex("SiteId", "Label", "IsActive")
                        .HasDatabaseName("IX_courts_site_label_active");

                    b.ToTable("courts", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Site.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("postcode");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("street");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("street_number");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_sites_city_search");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_sites_country_search");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_sites_created_at_utc");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_sites_is_active_filter");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_sites_name_search");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_sites_updated_at_utc");

                    b.HasIndex("CreatedAtUtc", "Id")
                        .HasDatabaseName("IX_sites_created_id_pagination");

                    b.HasIndex("Name", "City")
                        .IsUnique()
                        .HasDatabaseName("IX_sites_name_city_unique");

                    b.HasIndex("IsActive", "City", "Country")
                        .HasDatabaseName("IX_sites_active_location");

                    b.ToTable("sites", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Site.SiteClosure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<Guid[]>("AffectedCourtIds")
                        .HasColumnType("uuid[]")
                        .HasColumnName("affected_court_ids");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<TimeOnly?>("ModifiedClosingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("modified_closing_time");

                    b.Property<TimeOnly?>("ModifiedOpeningTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("modified_opening_time");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("reason");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AffectedCourtIds")
                        .HasDatabaseName("IX_site_closures_affected_courts");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("AffectedCourtIds"), "gin");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_site_closures_created_at_utc");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("IX_site_closures_end_date");

                    b.HasIndex("Reason")
                        .HasDatabaseName("IX_site_closures_reason");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_site_closures_site_id");

                    b.HasIndex("StartDate")
                        .HasDatabaseName("IX_site_closures_start_date");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_site_closures_type");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_site_closures_updated_at_utc");

                    b.HasIndex("SiteId", "StartDate", "EndDate")
                        .HasDatabaseName("IX_site_closures_site_period");

                    b.HasIndex("SiteId", "Type", "StartDate", "EndDate")
                        .HasDatabaseName("IX_site_closures_site_type_period");

                    b.ToTable("site_closures", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Site.SiteSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<int[]>("ApplicableDays")
                        .HasColumnType("integer[]")
                        .HasColumnName("applicable_days");

                    b.Property<TimeOnly>("ClosingTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("closing_time");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("OpeningTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opening_time");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date")
                        .HasColumnName("valid_until");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("IX_site_schedules_created_at_utc");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_site_schedules_is_active");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("IX_site_schedules_site_id");

                    b.HasIndex("UpdatedAtUtc")
                        .HasDatabaseName("IX_site_schedules_updated_at_utc");

                    b.HasIndex("ValidFrom", "ValidUntil")
                        .HasDatabaseName("IX_site_schedules_validity_period");

                    b.HasIndex("SiteId", "Priority", "IsActive")
                        .HasDatabaseName("IX_site_schedules_site_priority_active");

                    b.HasIndex("SiteId", "ValidFrom", "Priority")
                        .HasDatabaseName("IX_site_schedules_site_valid_priority");

                    b.HasIndex("SiteId", "ValidFrom", "ValidUntil", "IsActive")
                        .HasDatabaseName("IX_site_schedules_overlap_detection");

                    b.ToTable("site_schedules", "public");
                });

            modelBuilder.Entity("PadTime.Domain.Booking.Participant", b =>
                {
                    b.HasOne("PadTime.Domain.Booking.Match", null)
                        .WithMany("Participants")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadTime.Domain.Members.Member", b =>
                {
                    b.OwnsOne("PadTime.Domain.Members.Matricule", "Matricule", b1 =>
                        {
                            b1.Property<Guid>("MemberId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("matricule");

                            b1.HasKey("MemberId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("members", "public");

                            b1.WithOwner()
                                .HasForeignKey("MemberId");
                        });

                    b.Navigation("Matricule")
                        .IsRequired();
                });

            modelBuilder.Entity("PadTime.Domain.Site.Court", b =>
                {
                    b.HasOne("PadTime.Domain.Site.Site", null)
                        .WithMany("Courts")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadTime.Domain.Site.SiteClosure", b =>
                {
                    b.HasOne("PadTime.Domain.Site.Site", null)
                        .WithMany("Closures")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadTime.Domain.Site.SiteSchedule", b =>
                {
                    b.HasOne("PadTime.Domain.Site.Site", null)
                        .WithMany("Schedules")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PadTime.Domain.Booking.Match", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("PadTime.Domain.Site.Site", b =>
                {
                    b.Navigation("Closures");

                    b.Navigation("Courts");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
